version: '3.8'
services:

  #Production PHP Service
  app_prod:
    build:
      context: .
      dockerfile: ../dockerfiles/php80.dockerfile
      args:
        user: bible
        uid: 1000
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    restart: unless-stopped
    tty: true
    user: root
    working_dir: /var/www
    volumes:
      - ${PATH_BIBLE}:/var/www
      - ./.docker/laravel/.env:/var/www/.env
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/php/local.conf:/usr/local/etc/php-fpm.d/local.conf
    networks:
      - overlay
      - inside

  #Production Nginx Service
  nginx_prod:
    image: nginx:alpine
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    restart: unless-stopped
    tty: true
    volumes:
      - ${PATH_BIBLE}:/var/www
      - ./.docker/nginx/conf.production/:/etc/nginx/conf.d/
    networks:
      - overlay
      - inside

  #Production PHP Service
  app_dev:
    build:
      context: .
      dockerfile: ../dockerfiles/php80.dockerfile
      args:
        user: bible
        uid: 1000
    restart: unless-stopped
    tty: true
    user: root
    working_dir: /var/www
    volumes:
      - ${PATH_BIBLE_DEV}:/var/www
      - ./.docker/laravel/.env:/var/www/.env
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/php/local.conf:/usr/local/etc/php-fpm.d/local.conf
    networks:
      - overlay
      - inside

  #Production Nginx Service
  nginx_dev:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ${PATH_BIBLE_DEV}:/var/www
      - ./.docker/nginx/conf.development/:/etc/nginx/conf.d/
    networks:
      - overlay
      - inside

  #Haproxy
  proxy:
    build:
      context: ./.docker/haproxy
      dockerfile: ../../../dockerfiles/haproxy.dockerfile
    deploy:
      mode: global
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    dns: 127.0.0.11
    networks:
      - overlay

#Docker Networks
networks:
  overlay:
    driver: overlay
    attachable: true
  inside:
    driver: bridge    