version: "3.8"
services:
  #Epiloum Dev Blog
  blog_web:
    image: wordpress:5.8.1
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PSWD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: dev_
    volumes:
      - ${PATH_BLOG}/module:/var/www/html/module
      - ${PATH_BLOG}/wp-content:/var/www/html/wp-content
    networks:
      - overlay

  #Widget PHP-fpm
  widget_php:
    image: widget_php:latest
    build:
      context: .
      dockerfile: ../dockerfiles/php80.dockerfile
      args:
        user: bible
        uid: 1000
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    restart: always
    tty: true
    user: root
    working_dir: /var/www/html
    volumes:
      - ${PATH_WIDGET}:/var/www/html
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.widget/local.ini
      - ./.docker/php/local.conf:/usr/local/etc/php-fpm.d/local.conf
    networks:
      - overlay

  #Widget Nginx Service
  widget_nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    restart: always
    tty: true
    volumes:
      - ${PATH_WIDGET}:/var/www/html
      - ./.docker/nginx/conf.widget/:/etc/nginx/conf.d/
    networks:
      - overlay

  #Sandbox php-fpm
  sandbox_php:
    image: sandbox_php:latest
    build:
      context: .
      dockerfile: ../dockerfiles/php80.dockerfile
      args:
        user: bible
        uid: 1000
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    restart: always
    tty: true
    user: root
    working_dir: /var/www/html
    volumes:
      - ${PATH_SANDBOX}:/var/www/html
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.widget/local.ini
      - ./.docker/php/local.conf:/usr/local/etc/php-fpm.d/local.conf
    networks:
      - overlay

  #Sandbox Nginx Service
  sandbox_nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    restart: always
    tty: true
    volumes:
      - ${PATH_SANDBOX}:/var/www/html
      - ./.docker/nginx/conf.sandbox/:/etc/nginx/conf.d/
    networks:
      - overlay

  #Production PHP Service
  bible_prod_php:
    image: bible_prod_php:latest
    build:
      context: .
      dockerfile: ../dockerfiles/php80.dockerfile
      args:
        user: bible
        uid: 1000
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    restart: always
    tty: true
    user: root
    working_dir: /var/www
    volumes:
      - ${PATH_BIBLE}:/var/www
      - ./.docker/bible_laravel/.env:/var/www/.env
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/php/local.conf:/usr/local/etc/php-fpm.d/local.conf
    networks:
      - overlay

  #Production Nginx Service
  nginx_prod:
    image: nginx:alpine
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    restart: always
    tty: true
    volumes:
      - ${PATH_BIBLE}:/var/www
      - ./.docker/nginx/conf.bible.production/:/etc/nginx/conf.d/
    networks:
      - overlay

  #Production PHP Service
  bible_dev_php:
    image: bible_dev_php:latest
    build:
      context: .
      dockerfile: ../dockerfiles/php80.dockerfile
      args:
        user: bible
        uid: 1000
    restart: always
    tty: true
    user: root
    working_dir: /var/www
    volumes:
      - ${PATH_BIBLE_DEV}:/var/www
      - ./.docker/bible_laravel/.env:/var/www/.env
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/php/local.conf:/usr/local/etc/php-fpm.d/local.conf
    networks:
      - overlay

  #Production Nginx Service
  nginx_dev:
    image: nginx:alpine
    restart: always
    tty: true
    volumes:
      - ${PATH_BIBLE_DEV}:/var/www
      - ./.docker/nginx/conf.bible.development/:/etc/nginx/conf.d/
    networks:
      - overlay

  #Haproxy
  proxy:
    image: epiloum_proxy:latest
    build:
      context: ./.docker/haproxy
      dockerfile: ../../../dockerfiles/haproxy.dockerfile
    deploy:
      mode: global
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    dns: 127.0.0.11
    networks:
      - overlay

  #PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - target: 80
        published: 49080
        protocol: tcp
        mode: host
    environment:
      PMA_HOST: ${DB_HOST}
    networks:
      - overlay

#Docker Networks
networks:
  overlay:
    driver: overlay
    attachable: true
